### ISSUE TITLE
Deploy develop branch to AWS EC2

### ISSUE THREAD

**Issue by yellalena** [catbytes-community/webplatform-backend#6]
develop branch will be treated as pre-prod at the moment, so the deployed version should be available to  frontend team -> need to share the host. (**Marina**)

set up automatic deployment or (for now) provide an instruction for the team (**Aliona**)

**Comment by marinacatbytes** [comment]
Completed, develop environment is deployed to AWS EC2 and running with pm2 helper service.
Public IP: http://18.212.59.47
Please note that https will not work as SSL not configured on dev env
